services:
  ollama:
    image: ollama/ollama:latest
    container_name: mtr-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - mtr-network
    restart: unless-stopped

  chatbot:
    build: .
    container_name: mtr-chatbot
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - pip_cache:/root/.cache/pip
      - chroma_cache:/root/.cache/chroma
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/app
      - OLLAMA_CHAT_MODEL=deepseek-r1:1.5b
    depends_on:
      - ollama
    networks:
      - mtr-network
    restart: unless-stopped
    command: >
      bash -c "
        streamlit run frontend/frontend.py --server.address 0.0.0.0 --server.port 8501
      "
  pdf-server:
    image: nginx:alpine
    container_name: mtr-pdf-server
    ports:
      - "8502:80"
    volumes:
      - ./.data/original:/usr/share/nginx/html:ro
    networks:
      - mtr-network
    restart: unless-stopped
    command: /bin/sh -c "echo 'server { listen 80; location /pdfs/ { alias /usr/share/nginx/html/; add_header Access-Control-Allow-Origin * always; add_header Access-Control-Allow-Methods GET,OPTIONS always; add_header Access-Control-Allow-Headers Range always; if (\$$request_method = OPTIONS) { return 204; } } }' > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

volumes:
  ollama_data:
  pip_cache:
  chroma_cache:


networks:
  mtr-network:
    driver: bridge
